interface CountryProps {
  /** 2-letter country code */
  country: string;
  /** If true, only show the flag (otherwise puts the name after the flag) */
  flagOnly?: boolean;
}

/**
 * Display a country's unicode flag and possibly the name.
 */
export function Country(props: CountryProps) {
  const { country, flagOnly } = props;

  if (!/^[a-z]{2}$/i.test(country)) {
    throw new Error(`Invalid country code: ${country}`);
  }

  const countryName = getCountryName(country);

  // https://stackoverflow.com/questions/24050671/how-to-put-japan-flag-character-in-a-string
  const flag = getRegionalIndicatorSymbol(country[0]) + getRegionalIndicatorSymbol(country[1]);

  return flagOnly ? (
    <span title={countryName}>{flag}</span>
  ) : (
    <>
      <span aria-hidden>{flag}</span> {countryName}
    </>
  );
}

function getRegionalIndicatorSymbol(letter: string) {
  return String.fromCodePoint(0x1f1e6 - 65 + letter.toUpperCase().charCodeAt(0));
}

function getCountryName(countryCode: string) {
  const country = countries[countryCode.toUpperCase()];
  if (!country) {
    throw new Error(`Unknown country code (add it in the Country component): ${countryCode}`);
  }
  return country;
}

const countries: Record<string, string | undefined> = {
  AT: 'Austria',
  AU: 'Australia',
  BE: 'Belgium',
  CA: 'Canada',
  CH: 'Switzerland',
  CO: 'Colombia',
  CU: 'Cuba',
  CZ: 'Czechia',
  DE: 'Germany',
  DK: 'Denmark',
  EC: 'Ecuador',
  ER: 'Eritrea',
  ES: 'Spain',
  FR: 'France',
  GB: 'United Kingdom',
  HU: 'Hungary',
  IT: 'Italy',
  LV: 'Latvia',
  MU: 'Mauritius',
  MX: 'Mexico',
  NL: 'Netherlands',
  NO: 'Norway',
  NZ: 'New Zealand',
  PL: 'Poland',
  PT: 'Portugal',
  RU: 'Russia',
  SI: 'Slovenia',
  US: 'United States',
  // Commenting out the unused countries so they're removed during bundling
  // AD: 'Andorra',
  // AE: 'United Arab Emirates',
  // AF: 'Afghanistan',
  // AG: 'Antigua and Barbuda',
  // AI: 'Anguilla',
  // AL: 'Albania',
  // AM: 'Armenia',
  // AO: 'Angola',
  // AR: 'Argentina',
  // AW: 'Aruba',
  // AZ: 'Azerbaijan',
  // BA: 'Bosnia and Herzegovina',
  // BB: 'Barbados',
  // BD: 'Bangladesh',
  // BF: 'Burkina Faso',
  // BG: 'Bulgaria',
  // BH: 'Bahrain',
  // BI: 'Burundi',
  // BJ: 'Benin',
  // BL: 'Saint Barthélemy',
  // BM: 'Bermuda',
  // BN: 'Brunei',
  // BO: 'Bolivia',
  // BQ: 'Caribbean Netherlands',
  // BR: 'Brazil',
  // BS: 'Bahamas',
  // BT: 'Bhutan',
  // BV: 'Bouvet Island',
  // BW: 'Botswana',
  // BY: 'Belarus',
  // BZ: 'Belize',
  // CC: 'Cocos (Keeling) Islands',
  // CD: 'DR Congo',
  // CF: 'Central African Republic',
  // CG: 'Republic of the Congo',
  // CI: 'Ivory Coast',
  // CK: 'Cook Islands',
  // CL: 'Chile',
  // CM: 'Cameroon',
  // CN: 'China',
  // CR: 'Costa Rica',
  // CV: 'Cape Verde',
  // CW: 'Curaçao',
  // CX: 'Christmas Island',
  // CY: 'Cyprus',
  // DJ: 'Djibouti',
  // DM: 'Dominica',
  // DO: 'Dominican Republic',
  // DZ: 'Algeria',
  // EE: 'Estonia',
  // EG: 'Egypt',
  // EH: 'Western Sahara',
  // ET: 'Ethiopia',
  // FI: 'Finland',
  // FJ: 'Fiji',
  // FK: 'Falkland Islands',
  // FM: 'Micronesia',
  // FO: 'Faroe Islands',
  // GA: 'Gabon',
  // GD: 'Grenada',
  // GE: 'Georgia',
  // GF: 'French Guiana',
  // GG: 'Guernsey',
  // GH: 'Ghana',
  // GI: 'Gibraltar',
  // GL: 'Greenland',
  // GM: 'Gambia',
  // GN: 'Guinea',
  // GP: 'Guadeloupe',
  // GQ: 'Equatorial Guinea',
  // GR: 'Greece',
  // GS: 'South Georgia',
  // GT: 'Guatemala',
  // GU: 'Guam',
  // GW: 'Guinea-Bissau',
  // GY: 'Guyana',
  // HK: 'Hong Kong',
  // HM: 'Heard Island and McDonald Islands',
  // HN: 'Honduras',
  // HR: 'Croatia',
  // HT: 'Haiti',
  // ID: 'Indonesia',
  // IE: 'Ireland',
  // IL: 'Israel',
  // IM: 'Isle of Man',
  // IN: 'India',
  // IO: 'British Indian Ocean Territory',
  // IQ: 'Iraq',
  // IR: 'Iran',
  // IS: 'Iceland',
  // JE: 'Jersey',
  // JM: 'Jamaica',
  // JO: 'Jordan',
  // JP: 'Japan',
  // KE: 'Kenya',
  // KG: 'Kyrgyzstan',
  // KH: 'Cambodia',
  // KI: 'Kiribati',
  // KM: 'Comoros',
  // KN: 'Saint Kitts and Nevis',
  // KP: 'North Korea',
  // KR: 'South Korea',
  // KW: 'Kuwait',
  // KY: 'Cayman Islands',
  // KZ: 'Kazakhstan',
  // LA: 'Laos',
  // LB: 'Lebanon',
  // LC: 'Saint Lucia',
  // LI: 'Liechtenstein',
  // LK: 'Sri Lanka',
  // LR: 'Liberia',
  // LS: 'Lesotho',
  // LT: 'Lithuania',
  // LU: 'Luxembourg',
  // LY: 'Libya',
  // MA: 'Morocco',
  // MC: 'Monaco',
  // MD: 'Moldova',
  // ME: 'Montenegro',
  // MF: 'Saint Martin',
  // MG: 'Madagascar',
  // MH: 'Marshall Islands',
  // MK: 'North Macedonia',
  // ML: 'Mali',
  // MM: 'Myanmar',
  // MN: 'Mongolia',
  // MO: 'Macau',
  // MP: 'Northern Mariana Islands',
  // MQ: 'Martinique',
  // MR: 'Mauritania',
  // MS: 'Montserrat',
  // MT: 'Malta',
  // MV: 'Maldives',
  // MW: 'Malawi',
  // MY: 'Malaysia',
  // MZ: 'Mozambique',
  // NA: 'Namibia',
  // NC: 'New Caledonia',
  // NE: 'Niger',
  // NF: 'Norfolk Island',
  // NG: 'Nigeria',
  // NI: 'Nicaragua',
  // NP: 'Nepal',
  // NR: 'Nauru',
  // NU: 'Niue',
  // OM: 'Oman',
  // PA: 'Panama',
  // PE: 'Peru',
  // PF: 'French Polynesia',
  // PG: 'Papua New Guinea',
  // PH: 'Philippines',
  // PK: 'Pakistan',
  // PM: 'Saint Pierre and Miquelon',
  // PN: 'Pitcairn Islands',
  // PR: 'Puerto Rico',
  // PS: 'Palestine',
  // PW: 'Palau',
  // PY: 'Paraguay',
  // QA: 'Qatar',
  // RE: 'Réunion',
  // RO: 'Romania',
  // RS: 'Serbia',
  // RW: 'Rwanda',
  // SA: 'Saudi Arabia',
  // SB: 'Solomon Islands',
  // SC: 'Seychelles',
  // SD: 'Sudan',
  // SE: 'Sweden',
  // SG: 'Singapore',
  // SH: 'Saint Helena, Ascension and Tristan da Cunha',
  // SJ: 'Svalbard and Jan Mayen',
  // SK: 'Slovakia',
  // SL: 'Sierra Leone',
  // SM: 'San Marino',
  // SN: 'Senegal',
  // SO: 'Somalia',
  // SR: 'Suriname',
  // SS: 'South Sudan',
  // ST: 'São Tomé and Príncipe',
  // SV: 'El Salvador',
  // SX: 'Sint Maarten',
  // SY: 'Syria',
  // SZ: 'Eswatini',
  // TC: 'Turks and Caicos Islands',
  // TD: 'Chad',
  // TG: 'Togo',
  // TH: 'Thailand',
  // TJ: 'Tajikistan',
  // TK: 'Tokelau',
  // TL: 'Timor-Leste',
  // TM: 'Turkmenistan',
  // TN: 'Tunisia',
  // TO: 'Tonga',
  // TR: 'Türkiye',
  // TT: 'Trinidad and Tobago',
  // TV: 'Tuvalu',
  // TW: 'Taiwan',
  // TZ: 'Tanzania',
  // UA: 'Ukraine',
  // UG: 'Uganda',
  // UY: 'Uruguay',
  // UZ: 'Uzbekistan',
  // VA: 'Vatican City',
  // VC: 'Saint Vincent and the Grenadines',
  // VE: 'Venezuela',
  // VG: 'British Virgin Islands',
  // VI: 'United States Virgin Islands',
  // VN: 'Vietnam',
  // VU: 'Vanuatu',
  // WF: 'Wallis and Futuna',
  // WS: 'Samoa',
  // XK: 'Kosovo',
  // YE: 'Yemen',
  // YT: 'Mayotte',
  // ZA: 'South Africa',
  // ZM: 'Zambia',
  // ZW: 'Zimbabwe',
};
