name: Update rankings

on:
  # https://crontab-generator.org/
  # UCI updates: Tuesdays at 1:15am UTC (the 3/19 update was available by this time, but not an hour earlier)
  # - cron: '15 1 * * 2'
  # PCS updates: every day 11pm UTC
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'rankings'
  cancel-in-progress: false

permissions:
  contents: write
  # these are needed by the update-site workflow which this manually calls
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          corepack enable
          yarn

      - name: Update data
        run: yarn update-data

      - name: Commit and push changes
        run: |
          git config --global user.name 'EC'
          git config --global user.email '161985722+ec-bikes@users.noreply.github.com'
          git add data
          git commit -m "Update data"
          git push origin main

  # This won't be triggered on push since the push was by another action.
  # We also need to manually pass the correct ref, rather than the ref that triggered this workflow.
  call-update-site:
    uses: ./.github/workflows/update-site.yml
    needs: update
    with:
      ref: main
